version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
        update-types:
          - version-update:semver-patch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
